MODEL:
  META_ARCHITECTURE: "DispRCNN3D"
  DISPNET:
    MAX_DISP: 48
    MIN_DISP: -48
    RESOLUTIONS: (224,)
    LOSS_WEIGHT: 0.05
  #    TRAINED_MODEL: "models/psmnet_roi_freex_224_check/bestmodel.pth"
  POINTRCNN:
    MASK_THRESH: 0.5
    AUG_DATA: True
    MEAN_SIZE: [[1.52563191462, 1.62856739989, 3.88311640418]]
    RPN:
      FIXED: True
      LOSS_CLS: BinaryCrossEntropy
    #      LOSS_WEIGHT: [1.0, 0.2]
    RCNN:
      ENABLED: True
      CLS_FG_THRESH: 0.60
      REG_FG_THRESH: 0.55
      LOSS_CLS: BinaryCrossEntropy
      ROI_PER_IMAGE: 16
  MASK_ON: True
  STEREO_ON: True
  DET3D_ON: True
  DISPNET_ON: False
DATASETS:
  TRAIN: ("kitti_train_pob", )
  TEST: ("kitti_val_pob",)
#  TEST: ("kitti_train_vob", "kitti_val_vob",)
DATALOADER:
  SIZE_DIVISIBILITY: 1
  NUM_WORKERS: 8
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  SCHEDULER: OneCycleScheduler
#  MAX_ITER: 41400
  MAX_ITER: 62100
  IMS_PER_BATCH: 1
  TRAIN_PSM: False
  TRAIN_PC: True
  #  UNCERT_LOSS_WEIGHT: 2
  LOAD_OPTIMIZER: False
  LOAD_SCHEDULER: False
  FIX_DISPARITY: True
  FIX_POINTRCNN_RPN: True
  PRINT_INTERVAL: 1
  PRINT_ITERATION: False
  ALLOW_EXCEPTION: True
  DO_GRAD_CLIP: True
  REMOVE_EMPTY_ANNOTATIONS_TRAIN: False
  OFFLINE_2D_PREDICTIONS: "models/kitti/pob/idispnet/inference/kitti_%s_pob/predictions"
  CHECKPOINT_PERIOD: 414
TEST:
  IMS_PER_BATCH: 1
OUTPUT_DIR:
  "models/kitti/pob/rcnn"
INPUT:
  FLIP_PROB_TRAIN: 0.0
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 10000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 10000
  PIXEL_MEAN: [0.0, 0.0, 0.0]
  PIXEL_STD: [1.0, 1.0, 1.0]
  TO_BGR255: False